spring.application.name=hospitalManagement3

spring.datasource.url=jdbc:mysql://localhost:3306/hospital_database?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Diwa@0309

spring.jpa.hibernate.ddl-auto=update
